---
title: "Segregation in the Charlotte Mecklenburg Region"
author: "Eric Moore"
date: "`r Sys.Date()`"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Clear environment
rm(list = ls())

# Libraries
library(tidyverse)
library(readr)
library(reader)
library(censusapi)
library(data.table)
library(segregation)
library(tidycensus)
library(geojsonio)
library(broom)
library(tigris)
library(sf)
library(viridis)

# API Key Setup
#Sys.setenv(CENSUS_KEY="") # This will be the API key that is requested from the Census' website
```

## Acquiring Census Data

```{r census}
# Listing out the apis available to obtain data from
# datasets <- listCensusApis()

# These two commarnd provide more explicit detail on the details provided within particular datasets
# Here we are using the ACS 5-year estimates
# geo <- listCensusMetadata(name = "acs/acs5", vintage = 2021, type = "geographies")
# vars <- listCensusMetadata(name = "acs/acs5", vintage = 2021, type = "variables")

blkgroup <- getCensus(name = "acs/acs5", vintage = 2021, key = Sys.getenv("CENSUS_API_KEY"),
                   vars = c("B03002_001E", #Total Pop
                            "B03002_003E", "B03002_004E", "B03002_012E", #White, Black, Hispanic
                            "B03002_005E", "B03002_006E", "B03002_007E", "B03002_008E"), #Alaska Native, Asian, Hawaiian, Other
                   region = "block group:*", regionin = "state:37,45+county:*+tract:*")

Meck_21 <- blkgroup %>% unite('GEOID20', state:block_group, sep= "", remove=FALSE) %>% 
  unite('co_fips', state:county, sep= "", remove=FALSE) %>% 
  filter(co_fips %in% c("37025","37035","37045","37071","37109","37119","37159","37167","37179",
                        "45023","45057","45091") ) %>% 
  mutate(Othernon = sum(B03002_007E, B03002_008E, na.rm = TRUE)) %>%
  select(state:block_group, GEOID20, Total = B03002_001E, Whitenon = B03002_003E, Blknon = B03002_004E, Hisp = B03002_012E,
          Asiannon = B03002_006E) 
        # , AIANnon = B03002_005E, Othernon)

rm(datasets, geo, vars, blkgroup)
```

## Calculating Multi-Group Segregation and Diversity

```{r seg-div}

# Converting the dataset into a long format
Tractlev <- Meck_21 %>%
  dplyr::select(state, county, tract, block_group, GEOID20, Whitenon:Asiannon) %>%
    pivot_longer(cols = Whitenon:Asiannon, names_to = "Race", values_to = "Count")

# Running the mutal_within function of the segregation package
## this calculates the segregation between group and unit within each category (race)
SegNC <- mutual_within(
  data = Tractlev,
  group = "Race",
  unit = "GEOID20",
  weight = "Count",
  within = c("state", "county", "tract"),
  wide = TRUE
)

# Whats the difference?

# The entropy index is a measure of “evenness”—the extent to which groups are evenly distributed among organizational units
# Theil described entropy index as a measure of the average difference between a unit’s group proportions and that of the system as a whole

# The Entropy Score (Diversity):  a particular racial/ethnic group’s proportion of the whole geographic area population
    # The higher the number, the more diverse an area. 
    # The maximum level of entropy is given by the natural log of the number of groups used in the calculations. 
    # Not referred to as a measure of “segregation” because it does not measure the distribution of these groups across a metropolitan area

# Entropy index (Segregation): the weighted average deviation of each subunit’s entropy from the geo-wide entropy, expressed as a fraction of the geo-wide area’s total entropy
    # The index varies between 0, when all areas have the same composition as the entire metropolitan area (i.e., maximum integration), 
    # to a high of 1, when all areas contain one group only (maximum segregation).
    #  Measures how evenly groups are distributed across metropolitan area neighborhoods, regardless of the size of each of the groups
```

## Creating Basic Map

```{r shapefile}
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)

temp1 <- tracts("NC", cb=T)
temp2 <- tracts("SC", cb=T)
Shapefiles <- do.call(rbind, list(temp1, temp2))
rm(temp1, temp2)

MeckRegion <- Shapefiles %>% right_join(SegNC, by=c("STATEFP"="state", "COUNTYFP"="county", "TRACTCE"="tract"))
rm(Tractlev, SegNC, Shapefiles)
```

### Diversity
```{r}
ggplot(MeckRegion)+
  geom_sf(aes(fill=ent_ratio), color="white")+
  theme_void()+
  theme(panel.grid.major = element_line(colour = "transparent")) +
    scale_fill_viridis(option="viridis", name="Diversity") +
  labs(title = "Tract-level Diversity for the Mecklenburg Region (2021)", 
       caption = "Source: US Census/ACS5")
```

### Segregation
```{r}
ggplot(MeckRegion)+
  geom_sf(aes(fill=H), color="white")+
  theme_void()+
  theme(panel.grid.major = element_line(colour = "transparent"),
        legend.position = "right") +
    scale_fill_viridis(option="magma", name="Segregation") +
  labs(title = "Tract-level Segregation for the Mecklenburg Region (2021)", 
       caption = "Source: US Census/ACS5")
```

