---
title: "Test of Segregation Package"
author: "Eric Moore"
date: "`r Sys.Date()`"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Clear environment
rm(list = ls())

# Libraries
library(tidyverse)
library(readr)
library(reader)
library(censusapi)
library(data.table)
library(segregation)
library(tigris)
library(viridis)

# API Key Setup
Sys.setenv(CENSUS_KEY="020934bc9b3faa8c9f629492650c8eb446349f2d")
```

## Acquiring Census Data

```{r census}
# Listing out the apis available to obtain data from
datasets <- listCensusApis()

# These two commarnd provide more explicit detail on the details provided within particular datasets
# Here we are using the ACS 5-year estimates
geo <- listCensusMetadata(name = "acs/acs5", vintage = 2021, type = "geographies")
vars <- listCensusMetadata(name = "acs/acs5", vintage = 2021, type = "variables")

NCblkgroup <- getCensus(name = "acs/acs5", vintage = 2021, 
                   vars = c("B03002_001E", #Total Pop
                            "B03002_003E", "B03002_004E", "B03002_012E", #White, Black, Hispanic
                            "B03002_005E", "B03002_006E", "B03002_007E", "B03002_008E"), #Alaska Native, Asian, Hawaiian, Other
                   region = "block group:*", regionin = "state:37+county:*+tract:*")

NCrace21 <- NCblkgroup %>% unite('GEOID20', state:block_group, sep= "", remove=FALSE) %>% 
  mutate(Othernon = rowSums(across(c(B03002_007E:B03002_008E), na.rm=TRUE))) %>%
  select(state:block_group, GEOID20, Total = B03002_001E, Whitenon = B03002_003E, Blknon = B03002_004E, Hisp = B03002_012E,
          Asiannon = B03002_006E,  AIANnon = B03002_005E, Othernon)

rm(datasets, geo, vars, NCblkgroup)
```

## Calculating Multi-Group Segregation and Diversity

```{r seg-div}

# Converting the dataset into a long format
NCrace21 <- NCrace21 %>%
  dplyr::select(county, tract, block_group, GEOID20, Whitenon:AIANnon) %>%
    pivot_longer(cols = Whitenon:AIANnon, names_to = "Race", values_to = "Count")

# Running the mutal_within function of the segregation package
## this calculates the segregation between group and unit within each category (race)
SegNC <- mutual_within(
  data = NCrace21,
  group = "Race",
  unit = "GEOID20",
  weight = "Count",
  within = c("county", "tract"),
  wide = TRUE
)
```

## Creating Basic Map

```{r segmap}
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
NC <- tracts("NC", cb=T)

NC <- NC %>% left_join(SegNC, by=c("COUNTYFP"="county", "TRACTCE"="tract"))
rm(NCrace21, SegNC)

ggplot(NC)+
  geom_sf(aes(fill=H), color="white")+
  theme_void()+
  theme(panel.grid.major = element_line(colour = "transparent")) +
    scale_fill_viridis(option="magma", name="Standardized-H") +
  labs(title = "2021 North Carolina Tract-level Segregation", 
       caption = "Source: US Census/ACS5")
```

